### PR TITLE
Testcafe

### PR DESCRIPTION
**Pull request by brettz9**
- Testcafe tests (accessibility and basic tests)
- Linting: Add plugin for testcafe linting
- npm: Add test script

I just added one simple UI test for starters and then the accessibility tests, excluding one selector on the page, as that was added by the advertiser, and its accessibility problem is probably not under your control.

### CODE REVIEW

**Comment by brettz9** [comment]
Actually the npm `test` script should have `npm run docs-serve` in it as well, but not sure the best way to run these two in parallel: https://stackoverflow.com/questions/30950032/how-can-i-run-multiple-npm-scripts-in-parallel (the pipe answer doesn't seem to work as the test script appears to be unable to finish).

Also, I sometimes get a message that there is a color contrast issue. But at least the test highlights the issue.

**Comment by wenzhixin** [comment]
Great job, I will test this PR.

**Comment by wenzhixin** [comment]
I found the [start-server-and-test](https://www.npmjs.com/package/start-server-and-test) lib that can solve the problem.

**Comment by wenzhixin** [comment]
Thanks for your contribution!

**Pull request merged**
