### PR TITLE
ES6

### PR DESCRIPTION
**Pull request by brettz9**
- Breaking change: Moved file to `dist/multiple-select-umd.js`; for the
new ES6 Modules build, must use `addMultipleSelect(jQuery)` to add
plugin to a jQuery instance.
- Build: Add Rollup (for ES6 Modules) with Babel and uglify
- Fix: Ensure additional arguments are passed (e.g., to `optionToHtml`)
when method passed in as string without preceding options object
- Refactoring: Move to ES6 (use templates over `sprintf`,
`String.prototype.normalize` over custom removeDiacritics, use `class`)
- Linting: Add ESLint
- Bower: Remove `bower.json` (service deprecated)
- Docs: Comment out a failing analytics file
- Demo: In place of keeping assets in repo (and to avoid more recent
browser restrictions on non-descendant paths), use `node_modules`
with static server
- npm: Bump jQuery version
- npm: Add `package-lock.json` per later versions of npm
- npm: Add scripts for docs, demo, static server, rollup, and eslint
- yarn: Add `yarn.lock` as alternative to npm
- gitignore: Add `node_modules`

There were a lot of changes to be made, so if you plan to pull you should have a good look at whether things are all still working as expected.

The only thing I didn't add to the commit which I know should be added is documentation for the fact that now, in order to be modular, for the ES6 Module build, one can pass in a jQuery instance to `addMultipleSelect()`. This allows one to write (modular) ES6 module code like this:

```js
import $ from 'jquery';
import addMultipleSelect from 'multiple-select';
addMultipleSelect($);

// Use `$` with the plug-in, and without introducing any globals
```

Let me know what you think.

### CODE REVIEW

**Comment by wenzhixin** [comment]
Because this PR has conflicts, I will pick the changes to #412.
Thanks for your contribution!

**Comment by brettz9** [comment]
Btw, while I did like having a demo where I could see all of the elements together, I must say your new site is quite attractive!

As far as the changes, I'd like to offer a few recommendations:

1. Choose a stricter eslint standard to catch many more bugs, and override as necessary. Some popular ones are airbnb's or "standard". My own config, eslint-config-ash-nazg  builds on "standard" to add more.
2. While using `String.prototype.normalize` as I did over your custom `removeDiacritics` does require an added polyfill for older browsers, it makes the source a lot cleaner and leaner for environments that support this method...
3. Please consider using semantic versioning in your version numbering, i.e., major.minor.patch like 2.3.1 should flag that this is the 2nd breaking version, that there have been 3 enhancement releases, and 1 patch fix to the last enhancement release.
4. Don't forget to either add `dist` or put it in `.gitignore`. I'd also like `package-lock.json` either added to the repo or ignored.
5. Please consider offering an ESM distribution as well as a UMD distribution. It is convenient, especially for demos that don't need to support older browsers, to be able to use ESM for clean modularity without needing to do one's own ESM build steps (it can save time in debugging even if one's production code has build steps). So my demo can just use `import './node_modules/multiple-select/dist/multiple-select-esm.js'` (though I'm admittedly at least forced to add jQuery to my HTML until it finally gets an ESM distribution build).
6. Please point to your main ESM file (source or dist, as you prefer) using `module` in `package.json` so any bundlers can automatically find the source.

Thanks!

**Comment by wenzhixin** [comment]
Thanks for your recommendations.
I will improve the feature what you said.

**Comment by brettz9** [comment]
It turns out the `String.prototype.normalize` polyfill may be too large, and browser support doesn't seem to be there yet (at least for IE), so I've crossed that off.

**Pull request closed without merging**
