### PR TITLE
Fix VirtualScroll

### PR DESCRIPTION
**Pull request by yoreek**
This fixes a bug when scrolling does not work if the number of lines is more than 2000.

### CODE REVIEW

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://multiple-select-live.wenzhixin.net.cn/) to show the problem. Thanks!

**Comment by yoreek** [comment]
> Please provide an [Online Example](https://multiple-select-live.wenzhixin.net.cn/) to show the problem. Thanks!

https://multiple-select-live.wenzhixin.net.cn/code/yoreek/17674

**Comment by wenzhixin** [comment]
After applying your modifications and verifying, you must still resolve an issue. The elements greater than 2000 are not being displayed.
https://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/17680

**Comment by yoreek** [comment]
> After applying your modifications and verifying, you must still resolve an issue. The elements greater than 2000 are not being displayed. https://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/17680

oh, sorry didn't see this, I'll try to find the problem

**Comment by yoreek** [comment]
Fixed

**Pull request closed without merging**
