### PR TITLE
Babel

### PR DESCRIPTION
**Pull request by brettz9**
- ~License: Rename license file to reflect type (MIT)~
- ~Build: Add `@babel/preset-env` with `.babelrc` so dist build will be more backward-compatible~ *(Handled in other branch)*
- Linting (package.json): Add recommended `engines`/`dependencies` fields
- ~Docs: Mention `@babel/polyfill` (may be required depending on which ES features you are using;
    e.g., `String.prototype.includes`)~ (*No need for polyfill*)
- ~npm: Add `package-lock.json` per later versions of npm~ *Already ignoring*
- Git: Add `dist` to ignore file
- Proper escaping (Avoid warnings from https://lgtm.com/projects/g/wenzhixin/multiple-select/alerts/?mode=list)

This is building on your `develop` branch. I didn't know if you wanted to add `dist` to ignore or add the `dist` files to the repo. An advantage of having them in the repo is that one can see whether diffs exist or not, and Github-based hosting will share these files, but it adds somewhat to the size.

I would make some other changes, but I didn't know, e.g., which ESLint config you wanted to use or how you wanted to add the additional Rollup (ESM) format.

### CODE REVIEW

**Comment by brettz9** [comment]
It's the default, yes, but this is kind of biased toward Unix systems. If one wants to choose a default opener for ".txt" files, one isn't able to do so. I also think having the type in the file name is convenient for quickly seeing the type of license that is in the repo. Github will still recognize it when it shows the type of license for your project. It is not that important though, so whatever you want.

**Comment by brettz9** [comment]
Btw, I just added one more commit inspired by https://lgtm.com/projects/g/wenzhixin/multiple-select/alerts/?mode=list . This site catches errors that even ESLint doesn't catch.

**Comment by brettz9** [comment]
By the way--I highly recommend testcafe to add some UI-based tests. This is a very nice and easy-to-use library and might protect from regressions.

**Comment by brettz9** [comment]
As far as this PR, the most critical is `@babel/preset-env`. Notice how it changes the `dist` files, e.g., so that `const` are converted to `var` for older browsers. If you wanted to support even older browsers, we should add a `browserslist: []` to `package.json` as per https://babeljs.io/docs/en/babel-preset-env#browserslist-integration to indicate which browsers the `dist` files will support. To cover all, you can add this to `package.json` (`browserslist: ["cover 100%"]`) and then rebuild your files.

**Comment by brettz9** [comment]
Btw, as far as my last commit, though I added the selector escaping, in my testing it wasn't actually needed; I think the quotation marks for `label[for="%s"]` obviate the need for escaping.

**Comment by wenzhixin** [comment]
> I highly recommend test case to add some UI-based tests.

I think it's a good idea, but I don't have much experience in this.

**Comment by brettz9** [comment]
Ok, I should be able to set up testcafe with a very basic test, and feel free to add to them as inspired.

**Comment by brettz9** [comment]
But let me know about these first:

1. Do you prefer I go back to `LICENSE`?
2. Do you have an opinion about what stricter ESLint config to use?
3. Do you want to support all older browsers, or only care about the last N versions, etc.?

**Comment by wenzhixin** [comment]
Yes, I think it's better to use `LICENSE` instead. 
You can see other repos:
* https://github.com/twbs/bootstrap
* https://github.com/vuejs/vue

**Comment by wenzhixin** [comment]
I understand what you mean, that's my fault, but add a polyfill as dependency maybe not a good idea.
You can check out this issue: https://github.com/wenzhixin/bootstrap-table/issues/4098.

I created a new PR #414 base on https://babeljs.io/docs/en/babel-preset-env. 
Can this solve the older browsers what you said?

**Comment by wenzhixin** [comment]
BTW, now you are collaborator, you can update the PR what I have created.

**Comment by brettz9** [comment]
Yes, your PR was good re: Babel and older browsers.

As far as @babel/polyfill, I hadn't been aware of that recent deprecation, but I've filed https://github.com/babel/babel/issues/9917 since core-js and regenerator-runtime unfortunately don't currently offer ESM browser builds (one has to do the building oneself rather than just including a pre-built polyfill file). But it looks like @babel/preset-env, with "usage" tries to auto-detect even the prototype method usage like `Array.prototype.includes`, so I think there  indeed may be no need for it anyways. Speaking of which, I think you can avoid those extra plugins in `bootstrap-table` too, if you use @babel/preset-env there in the same way.

If I make a new change, e.g., to add a new ESLint config, on which branch should I make the commit? On `master`, or make PRs, but just be aware I can modify your own PR branches?

**Comment by brettz9** [comment]
Ok, I've incorporated your changes. Please see if it is ok now.

**Pull request merged**
