### PR TITLE
fix #53. Now you can enable optgroup search with option 'filterGroup'

### LINKED ISSUE #53: Can we search?
If there is a long list of options, it's a bit difficult to scroll down and find the item. Is there a way to search?

### PR DESCRIPTION
**Pull request by FiloSpaTeam**

### CODE REVIEW

**Comment by kmgsoftware** [comment]
Not sure why this isn't in the actual script. Thanks for the fix!

**Comment by rp-21** [comment]
Please pull and merge this pull request this is very usefull

**Comment by wenzhixin** [comment]
Added this feature in the latest version: https://github.com/wenzhixin/multiple-select/blob/develop/CHANGELOG.md#130. Thanks for your contribution!

**Comment by sharathdaniel** [comment]
Any way to enable filtering both optgroup and sub items?

**Pull request closed without merging**
