### PR TITLE
Added bootstrap(v3, v4) themes

### LINKED ISSUE #481: Bootstrap form-control class is broken
Hi, I need to style multiple-select like bootstrap form-control. But if I set form-control class select element is broken, like on the screenshot. Is it possible to use form-control class or is it necessary to style it manually?
Screenshot (16)

### PR DESCRIPTION
**Pull request by wenzhixin**
Fix #481

Example: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/845

### CODE REVIEW

**Comment by camohub** [comment]
Is it in master? I see it is merged to develop and no commit in master..

**Comment by wenzhixin** [comment]
@camohub Will release in the next version.

**Comment by camohub** [comment]
When? Now I have a fix in css. But I have a lot of another work...

**Comment by wenzhixin** [comment]
Release v1.4.2 soon: https://github.com/wenzhixin/multiple-select/blob/develop/CHANGELOG.md

**Comment by wenzhixin** [comment]
1.4.2 released: http://multiple-select.wenzhixin.net.cn

**Pull request merged**
