### PR TITLE
Testing updates

### PR DESCRIPTION
**Pull request by brettz9**
- npm: Add missing peerDep. of testing
- Testing: Update axe per updated API and updated doc URL

### CODE REVIEW

**Comment by wenzhixin** [comment]
Thanks

**Comment by brettz9** [comment]
Sure, thank you! Btw, can I ask what you didn't like about the eslint config? I'd like to ensure it is meeting enough needs.

**Comment by wenzhixin** [comment]
Do you mean https://github.com/wenzhixin/multiple-select/commit/3d7ae14855e850f735fb502d8e7448814a0412a5?

One reason is that I think it depends on more libraries. In addition, it was removed because it did not resolve the error. You can try `yarn lint`.

**Comment by brettz9** [comment]
Right. Yeah, there are not fixers for all problems; one has to figure out for some why they are problems. While sometimes they may just be stylistic concerns--and those can be overridden in the eslint config if you don't like them--many times they are flagging problematic code, so I think they are worth it even if there is no fixer. But if you don't want extra devDeps, then yes, it does require them.

**Pull request merged**
